/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Figuras extends javax.swing.JFrame {

    /**
     * Creates new form Figuras
     */
    public Figuras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbase = new javax.swing.JTextField();
        txtaltura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtradio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbcuadrado = new javax.swing.JRadioButton();
        rbrectangulo = new javax.swing.JRadioButton();
        rbtriangulo = new javax.swing.JRadioButton();
        rbcirculo = new javax.swing.JRadioButton();
        cbarea = new javax.swing.JCheckBox();
        cbperimetro = new javax.swing.JCheckBox();
        btncalcular = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CÁLCULO DE AREAS Y PERIMETROS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE ENTRADA:"));

        jLabel2.setText("BASE:");

        jLabel3.setText("ALTURA:");

        jLabel4.setText("RADIO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(txtbase)))
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtradio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO DE FIGURA:"));

        rbcuadrado.setText("CUADRADO");
        rbcuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbcuadradoMouseClicked(evt);
            }
        });

        rbrectangulo.setText("RECTANGULO");
        rbrectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbrectanguloMouseClicked(evt);
            }
        });

        rbtriangulo.setText("TRIANGULO");
        rbtriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtrianguloMouseClicked(evt);
            }
        });

        rbcirculo.setText("CIRCULO");
        rbcirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbcirculoMouseClicked(evt);
            }
        });

        cbarea.setText("AREA");

        cbperimetro.setText("PERIMETRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcuadrado)
                    .addComponent(rbrectangulo)
                    .addComponent(rbtriangulo)
                    .addComponent(rbcirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbarea)
                    .addComponent(cbperimetro))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcuadrado)
                    .addComponent(cbarea))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbrectangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtriangulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cbperimetro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbcirculo))
        );

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btncalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double perimetro=0,area=0;
    
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        grupo.add(rbcuadrado);
        grupo.add(rbrectangulo);
        grupo.add(rbtriangulo);
        grupo.add(rbcirculo);
        
    }//GEN-LAST:event_formWindowActivated

    private void rbcuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbcuadradoMouseClicked
        // TODO add your handling code here:
        txtaltura.enable(false);
        txtradio.enable(false);
        txtbase.enable(true);
        //Borrar los datos que no se ocupan en la figura
        txtaltura.setText("");
        txtradio.setText("");
        
    }//GEN-LAST:event_rbcuadradoMouseClicked

    private void rbrectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbrectanguloMouseClicked
        // TODO add your handling code here:
        txtaltura.enable(true);
        txtradio.enable(false);
        txtbase.enable(true);
        //Borrar los datos que no se ocupan en la figura
        txtradio.setText("");
    }//GEN-LAST:event_rbrectanguloMouseClicked

    private void rbtrianguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtrianguloMouseClicked
        // TODO add your handling code here:
        txtaltura.enable(true);
        txtradio.enable(false);
        txtbase.enable(true);
        //Borrar los datos que no se ocupan en la figura
        txtradio.setText("");
    }//GEN-LAST:event_rbtrianguloMouseClicked

    private void rbcirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbcirculoMouseClicked
        // TODO add your handling code here:
         txtaltura.enable(false);
        txtradio.enable(true);
        txtbase.enable(false);
        //Borrar los datos que no se ocupan en la figura
        txtaltura.setText("");
        txtbase.setText("");
    }//GEN-LAST:event_rbcirculoMouseClicked

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        Resultados ventana= new Resultados();
        double base,altura,radio;
        
       perimetro=0;
        area=0;
        
        if(cbperimetro.isSelected()==true)
        {
            if(rbcuadrado.isSelected()==true)
            {
                base= Double.parseDouble(txtbase.getText());
                perimetro=4*base;
            }
            else
            if(rbrectangulo.isSelected()==true)
            {
                base= Double.parseDouble(txtbase.getText());
        altura= Double.parseDouble(txtaltura.getText());
       
                perimetro=(altura*2)+(base*2);
                
            }
            else
            if(rbtriangulo.isSelected()==true)
            {
                base= Double.parseDouble(txtbase.getText());
        altura= Double.parseDouble(txtaltura.getText());
       
                perimetro=2*altura+base;
            }
                else
                if(rbcirculo.isSelected()==true)
                {
                    
        radio= Double.parseDouble(txtradio.getText());
                perimetro =(3.1416*2*radio);
                }
        }
        if(cbarea.isSelected()==true)
        {
             if(rbcuadrado.isSelected()==true)
             {
                 base= Double.parseDouble(txtbase.getText());
       
               area=base*base;
             }
               else
            if(rbrectangulo.isSelected()==true)
            {
                base= Double.parseDouble(txtbase.getText());
        altura= Double.parseDouble(txtaltura.getText());
      
                area=base*altura;
            }
                else
            if(rbtriangulo.isSelected()==true)
            {
                base= Double.parseDouble(txtbase.getText());
        altura= Double.parseDouble(txtaltura.getText());
       
                area=(base*altura)/2;
            }
                else
                if(rbcirculo.isSelected()==true)
                {
                   
        radio= Double.parseDouble(txtradio.getText());
                area= 3.1416*radio*radio;
                }
        }
        if(rbcuadrado.isSelected()==true)
               ventana.figura="cuadrado";
            else
            if(rbrectangulo.isSelected()==true)
               ventana.figura="rectangulo";
            else
            if(rbtriangulo.isSelected()==true)
               ventana.figura="triangulo";
            else
                if(rbcirculo.isSelected()==true)
                ventana.figura="circulo";
        
        ventana.a=String.valueOf(area);
        ventana.p=String.valueOf(perimetro);
         ventana.setVisible(true);
    //    this.dispose();
        
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnsalir;
    private javax.swing.JCheckBox cbarea;
    private javax.swing.JCheckBox cbperimetro;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbcirculo;
    private javax.swing.JRadioButton rbcuadrado;
    private javax.swing.JRadioButton rbrectangulo;
    private javax.swing.JRadioButton rbtriangulo;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtbase;
    private javax.swing.JTextField txtradio;
    // End of variables declaration//GEN-END:variables
}
